### ISSUE TITLE
error in incoming mail

### ISSUE THREAD

**Issue by genesis231** [axel-angel/whatsapp-email-bridge#10]
``` yaml
reply: "saad.*********@gmail.com"
whatsapp:
    phone: "91903********"
    password: "xivOjMm*****************"
outgoing:
    with: SMTP
    host: "localhost"
    port: 25
    user: saad***@gmail.com
    pass: **************
    sendto: "saad****@gmail.com"
    ssl: 0
    force_starttls: 0
ingoing:
    # create an SMTP server
    with: SMTP
    host: localhost
    port: 25
    # create an LMTP server
    #with: LMTP
    #socket: "/home/saad/Desktop/whatsappp.sock"
```
