### ISSUE TITLE
mail doesn't match reply:

### ISSUE THREAD

**Issue by dreamflasher** [axel-angel/whatsapp-email-bridge#20]
I am getting 
`mail doesn't match reply:`
How can I debug what's going wrong?

**Comment by axel-angel** [comment]
It shouldn't require any hard debug, just look at the email address you used and look at the one that's specified in the config file, the `{}` are used to extract the variable part.

**Comment by dreamflasher** [comment]
Okay apparently this does not work with my setup as I would expect.
This is my setup (I am leaving out the irrelevant parts):

```
reply: "foobar+{}@gmail.com"

outgoing:
    host: smtp.gmail.com
    sendto: whatsapp@mydomain.com

ingoing: # pick one type below
    host: imap.gmail.com
```

So I am using one gmail account for IMAP outgoing/receiving. Then I have another account (because I don't want the email bridge to access all my emails) where I receive the messages. This is also hosted under gmail, and I allowed sending mails from this gmail account via the gmail account I use for whatsapp-email-bridge. And apparently when hitting reply the correct "from" is used, but excluding the +XXXX. Do I understand correctly that email bridge does an exact match on the "from" address? Is that necessary?
